#! /usr/bin/env python3

import os

p = int(os.popen("xbacklight -get").read())

if p < 10:
    print(f"󰃞 {p}", end = '')
elif p < 50:
    print(f"󰃟 {p}", end = '')
else:
    print(f"󰃠 {p}", end = '')