#!/bin/bash

while getopts p:a: flag
do
    case "${flag}" in
        p) path=${OPTARG};;
	a) alpha=${OPTARG};;
    esac
done
wal -i $path -a $alpha;
#wal -i $path;
cp $path ~/.local/share/bg
pkill dunst
qtile cmd-obj -o cmd -f restart
