#!/usr/bin/env python3


import sys
import os

if len(sys.argv) == 2:
    path = sys.argv[1]
else:
    print("usage-> wallpaper abspath")
    exit()

os.system(f"cp {path} ~/Pictures/Wallpapers/.cur")
os.system(f"wal -i {path} -a 60")
os.system(f"killall swaybg")
os.system(f"swaybg -m fill --image {path} & disown")
os.system("bash ~/.mysrcs/waybar.start")
