#!/bin/sh
exec swayidle -w \
  timeout 180 'brightnessctl s $(($(brightnessctl g)/2))' \
    resume 'brightnessctl s $(($(brightnessctl g)*2))' \
  timeout 300 '~/.local/share/scripts/lock/launch-swaylock'\
  timeout 480 'niri msg action power-off-monitors' \
    resume 'niri msg action power-on-monitors' \
