# Variable (including colors)
source = ~/.config/hypr/hyprland/var.conf

# Other options (uses colors)
source = ~/.config/hypr/hyprland/options.conf

# lone rule so no seperate file for you
windowrulev2 = suppressevent maximize, class:.*
windowrulev2 = float, class:waypaper

# Env
source = ~/.config/hypr/hyprland/env.conf
# Keybinds
source = ~/.config/hypr/hyprland/keybinds.conf
# Auto Start
source = ~/.config/hypr/hyprland/autostart.conf


