exec-once = dbus-update-activation-environment --all
exec-once = swaync
exec-once = pipewire
exec-once = /usr/libexec/polkit-gnome-authentication-agent-1
exec-once=swww-daemon && swww img ~/.local/share/bg
exec-once=hypridle
exec = ~/.local/bin/launch-waybar
